// MigrationReport.tsx — Exportable migration report (Markdown + PDF via jsPDF)
import { useState } from "react";
import type{ ParsedContract } from "../utils/solidityParser";
import type{ MappingRule } from "../utils/mappingRules";
import type{ AnchorSkeleton } from "../utils/anchorGenerator";
import type{ CostEstimate } from "../utils/costCalculator";

interface Props {
  parsed: ParsedContract;
  mappings: MappingRule[];
  skeleton: AnchorSkeleton | null;
  costs: CostEstimate | null;
}

// ── Markdown generator ────────────────────────────────────────────────
// Uses array push to avoid nested template literal / backtick issues.
function buildMarkdown(
  parsed: ParsedContract,
  mappings: MappingRule[],
  skeleton: AnchorSkeleton | null,
  costs: CostEstimate | null,
): string {
  const contract = parsed.contracts[0];
  const now = new Date().toISOString().split("T")[0];
  const publicFns = contract?.functions.filter(
    (f) => f.visibility === "public" || f.visibility === "external",
  ) ?? [];

  const lines: string[] = [];
  const p = (...args: string[]) => lines.push(...args);
  const sep = () => { p("", "---", ""); };
  const tick = "`";
  const fence = "```";

  // Header
  p("# Migration Report — " + (contract?.name ?? "Unknown"));
  p("*Generated by Sunrise Migration Copilot · " + now + "*");
  sep();

  // 1. Contract Analysis
  p("## 1. Contract Analysis", "");
  p("| Property | Value |", "|---|---|");
  p("| Contract Name | " + tick + (contract?.name ?? "") + tick + " |");
  p("| Solidity Pragma | " + tick + parsed.pragmaVersion + tick + " |");
  p("| Line Count | " + parsed.lineCount + " |");
  p("| Complexity | " + parsed.complexity + " |");
  p("| ERC-20 | " + (parsed.isERC20 ? "Yes" : "No") + " |");
  p("| ERC-721 | " + (parsed.isERC721 ? "Yes" : "No") + " |");
  p("| Ownable | " + (parsed.hasOwnable ? "Yes" : "No") + " |");
  p("| Access Control | " + (parsed.hasAccessControl ? "Yes" : "No") + " |");
  p("");

  p("### State Variables (" + (contract?.stateVariables.length ?? 0) + ")", "");
  (contract?.stateVariables ?? []).forEach((v) => {
    const pdaNote = v.typeName.startsWith("mapping") ? " → **PDA per key on Solana**" : "";
    p("- " + tick + v.typeName + " " + v.name + tick + " — " + v.visibility + pdaNote);
  });
  p("");

  p("### Public Functions (" + publicFns.length + ")", "");
  publicFns.forEach((f) => {
    const params = f.parameters.map((pp) => pp.typeName + " " + pp.name).join(", ");
    p("- " + tick + f.name + "(" + params + ")" + tick + " → " + tick + f.stateMutability + tick);
  });
  p("");

  p("### Events (" + (contract?.events.length ?? 0) + ")", "");
  (contract?.events ?? []).forEach((e) => {
    p("- " + tick + e.name + tick + " → Anchor " + tick + "#[event]" + tick + " + " + tick + "emit!()" + tick);
  });
  sep();

  // 2. Mappings
  p("## 2. EVM → Solana Mappings", "");
  mappings.slice(0, 12).forEach((m) => {
    p("### " + m.evmConcept + " → " + m.solanaConcept);
    p("**Category:** " + m.category + "  **Complexity:** " + m.complexity, "");
    p(m.rationale, "");
    if (m.anchor_snippet) {
      p(fence + "rust");
      p(m.anchor_snippet);
      p(fence, "");
    }
  });
  sep();

  // 3. Anchor Skeleton
  p("## 3. Anchor Skeleton", "");
  p("**Program name:** " + tick + (skeleton?.programName ?? "unknown") + tick, "");
  p("### Instructions", "");
  (skeleton?.instructions ?? []).forEach((i) => p("- " + tick + i + tick));
  p("");
  p("### Account Structs", "");
  (skeleton?.accountStructs ?? []).forEach((s) => p("- " + tick + s + tick));
  p("");
  p("### Generated Files", "");
  (skeleton?.files ?? []).forEach((f) => p("- " + tick + f.filename + tick + " (" + f.language + ")"));
  p("");
  if (skeleton?.files[0]) {
    p("#### lib.rs (preview)", "");
    p(fence + "rust");
    p(skeleton.files[0].content.slice(0, 600) + "\n// ...");
    p(fence);
  }
  sep();

  // 4. Token Migration
  p("## 4. Token Migration — Wormhole NTT + Sunrise", "");
  p("### Migration Steps", "");
  const steps = [
    "Take holder snapshot — record all current ERC-20 balances",
    "Deploy SPL mint — " + tick + "spl-token create-token" + tick + " on Solana",
    "Configure Wormhole NTT — deploy NTT Manager on EVM + NTT Hub on Solana",
    "Test on testnet — run " + tick + "npx tsx wormhole-integration/migrate-token.ts" + tick,
    "Holder distribution — airdrop SPL tokens matching snapshot balances",
    "Register with Sunrise — apply for day-one AMM liquidity pool",
    "Revoke EVM mint — lock or renounce minting on legacy contract",
    "Mainnet migration — execute live NTT transfer",
    "Liquidity bootstrapping — Sunrise provides canonical DEX route",
  ];
  steps.forEach((s, i) => p((i + 1) + ". " + s));
  p("");
  p("### Sunrise Integration", "");
  p("> Post-migration, coordinate with Sunrise for day-one liquidity pools.");
  p("> Sunrise provides the canonical liquidity route for newly bridged assets entering the Solana ecosystem.");
  p("");
  p("- Apply: https://www.sunrisedefi.com/");
  p("- Twitter: https://x.com/Sunrise_DeFi");
  sep();

  // 5. Cost Comparison
  p("## 5. Cost Comparison", "");
  p("| Operation | Ethereum (avg) | Solana | Savings |", "|---|---|---|---|");
  const evmDeploy = costs ? costs.ethereum.deploymentCost.toFixed(2) : "150.00";
  const solDeploy = costs ? costs.solana.deploymentCost.toFixed(4) : "0.0026";
  const evmXfer   = costs ? costs.ethereum.perTxCost.toFixed(2) : "2.30";
  const evmMo     = costs ? (costs.ethereum.perTxCost * 10000).toFixed(0) : "23000";
  const solMo     = costs ? (costs.solana.perTxCost * 10000).toFixed(2) : "0.90";
  const annSave   = costs ? (costs.savingsUSD * 12).toFixed(0) : "276000";
  p("| Deploy | ~$" + evmDeploy + " | ~$" + solDeploy + " | ~99% |");
  p("| Transfer | ~$" + evmXfer + " | ~$0.0001 | ~99.9% |");
  p("| Monthly 10K txs | ~$" + evmMo + " | ~$" + solMo + " | ~99.9% |");
  p("");
  p("**Estimated annual savings: $" + annSave + "**");
  sep();

  // 6. Checklist
  p("## 6. Migration Checklist", "");
  const checklist = [
    { done: true,                  item: "Contract uploaded and parsed" },
    { done: mappings.length > 0,   item: "Mapping rules reviewed" },
    { done: skeleton !== null,     item: "Anchor skeleton generated" },
    { done: false, item: "Anchor skeleton reviewed and customized" },
    { done: false, item: "PDA seeds verified for uniqueness" },
    { done: false, item: "Account space calculations confirmed" },
    { done: false, item: "Error codes mapped from Solidity requires" },
    { done: false, item: "Unit tests written for all instructions" },
    { done: false, item: "Deployed and tested on devnet" },
    { done: false, item: "Security audit completed" },
    { done: false, item: "Token holder snapshot taken" },
    { done: false, item: "SPL mint deployed on mainnet" },
    { done: false, item: "Wormhole NTT manager configured" },
    { done: false, item: "Migration executed on testnet" },
    { done: false, item: "Migration executed on mainnet" },
    { done: false, item: "Applied to Sunrise for liquidity pool" },
  ];
  checklist.forEach((c) => p("- [" + (c.done ? "x" : " ") + "] " + c.item));
  sep();

  // 7. Resources
  p("## 7. Resources", "");
  p("| Resource | Link |", "|---|---|");
  [
    ["Anchor Docs",     "https://www.anchor-lang.com/"],
    ["Wormhole NTT",   "https://wormhole.com/docs/learn/messaging/native-token-transfers/"],
    ["Wormhole SDK",   "https://wormhole.com/docs/tools/typescript-sdk/get-started/"],
    ["Solana Cookbook", "https://solanacookbook.com/"],
    ["SPL Token",       "https://spl.solana.com/token"],
    ["Metaplex (NFTs)", "https://docs.metaplex.com/"],
    ["Sunrise DeFi",    "https://www.sunrisedefi.com/"],
  ].forEach(([name, url]) => p("| " + name + " | " + url + " |"));
  p("", "---");
  p("*Generated by Sunrise Migration Copilot — EVM → Solana migration toolkit*");

  return lines.join("\n");
}

// ── PDF generator (jsPDF via CDN) ─────────────────────────────────────
async function exportPDF(markdown: string, contractName: string) {
  // Load jsPDF dynamically from CDN at runtime (avoids npm dependency)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const dynamicImport = new Function("url", "return import(url)") as (url: string) => Promise<any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { jsPDF } = await dynamicImport("https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js") as any;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  const usableW = pageW - margin * 2;
  let y = margin;

  const addPage = () => { doc.addPage(); y = margin; };
  const checkPage = (needed: number) => { if (y + needed > 280) addPage(); };

  // Cover
  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, pageW, 60, "F");
  doc.setTextColor(247, 147, 26);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(`Migration Report`, margin, 25);
  doc.setFontSize(14);
  doc.setTextColor(200, 200, 200);
  doc.text(contractName, margin, 36);
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(`Sunrise Migration Copilot · ${new Date().toLocaleDateString()}`, margin, 47);
  y = 72;

  // Content — parse markdown into lines
  const lines = markdown.split("\n");
  doc.setTextColor(30, 30, 30);

  for (const line of lines) {
    if (line.startsWith("# ")) {
      checkPage(14);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(247, 147, 26);
      doc.text(line.replace(/^# /, ""), margin, y);
      y += 10; doc.setTextColor(30, 30, 30);
    } else if (line.startsWith("## ")) {
      checkPage(12);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(153, 69, 255);
      const heading = line.replace(/^## /, "");
      doc.text(heading, margin, y);
      doc.setDrawColor(153, 69, 255);
      doc.setLineWidth(0.3);
      doc.line(margin, y + 1.5, margin + doc.getTextWidth(heading), y + 1.5);
      y += 9; doc.setTextColor(30, 30, 30);
    } else if (line.startsWith("### ")) {
      checkPage(10);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(25, 200, 130);
      doc.text(line.replace(/^### /, ""), margin, y);
      y += 7; doc.setTextColor(30, 30, 30);
    } else if (line.startsWith("- ")) {
      checkPage(6);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      const wrapped = doc.splitTextToSize(line.replace(/^- /, "• "), usableW - 5);
      doc.text(wrapped, margin + 2, y);
      y += wrapped.length * 5;
    } else if (line.startsWith("|")) {
      // table row
      checkPage(6);
      const cells = line.split("|").filter(c => c.trim() && !c.trim().match(/^[-\s]+$/));
      if (cells.length >= 2) {
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        const colW = usableW / cells.length;
        cells.forEach((cell, ci) => {
          const isHeader = line.includes("---");
          if (isHeader) return;
          doc.setTextColor(ci === 0 ? 80 : 40, ci === 0 ? 80 : 40, ci === 0 ? 80 : 40);
          doc.text(cell.trim().replace(/\*\*/g,"").replace(/`/g,""), margin + ci * colW, y, { maxWidth: colW - 2 });
        });
        if (!line.includes("---")) y += 5.5;
      }
    } else if (line.startsWith("```")) {
      // skip code blocks in PDF (too complex)
    } else if (line.trim()) {
      checkPage(6);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(50, 50, 50);
      const clean = line.replace(/\*\*/g,"").replace(/`/g,"").replace(/^>\s*/,"").replace(/^\*(.+)\*$/,"$1");
      const wrapped = doc.splitTextToSize(clean, usableW);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 5;
    } else {
      y += 3;
    }
  }

  // Footer on each page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Sunrise Migration Copilot · Page ${i} of ${pageCount}`, margin, 290);
    doc.text("sunrisedefi.com", pageW - margin - 28, 290);
  }

  doc.save(`${contractName}-migration-report.pdf`);
}

// ── Component ─────────────────────────────────────────────────────────
export default function MigrationReport({ parsed, mappings, skeleton, costs }: Props) {
  const [showPreview, setShowPreview] = useState(false);
  const [exporting, setExporting] = useState<"md" | "pdf" | null>(null);
  const contract = parsed.contracts[0];
  const contractName = contract?.name ?? "Contract";
  const markdown = buildMarkdown(parsed, mappings, skeleton, costs);

  const downloadMD = () => {
    setExporting("md");
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${contractName}-migration-report.md`;
    a.click(); URL.revokeObjectURL(url);
    setTimeout(() => setExporting(null), 1000);
  };

  const downloadPDF = async () => {
    setExporting("pdf");
    try {
      await exportPDF(markdown, contractName);
    } catch (_err) {
      // Fallback: open in new window for printing
      const win = window.open("", "_blank");
      if (win) {
        win.document.write(`<html><head><title>${contractName} Migration Report</title><style>body{font-family:monospace;max-width:800px;margin:40px auto;white-space:pre-wrap}</style></head><body>${markdown.replace(/</g,"&lt;")}</body></html>`);
        win.print();
      }
    }
    setTimeout(() => setExporting(null), 2000);
  };

  const sections = [
    { icon: "🔍", title: "Contract Analysis",    items: [`${parsed.contracts.length} contracts`, `${contract?.functions.length ?? 0} functions`, `Complexity: ${parsed.complexity}`] },
    { icon: "🗺", title: "Mapping Rules",       items: [`${mappings.length} mappings generated`, `${mappings.filter(m => m.complexity === "high").length} high complexity`, `${mappings.filter(m => m.category === "token").length} token mappings`] },
    { icon: "⚓", title: "Anchor Skeleton",     items: skeleton ? [`${skeleton.files.length} files generated`, `${skeleton.instructions.length} instructions`, `Program: ${skeleton.programName}`] : ["Not generated"] },
    { icon: "💰", title: "Cost Analysis",       items: costs ? [`EVM deploy: $${costs.ethereum.deploymentCost.toFixed(2)}`, `Solana deploy: $${costs.solana.deploymentCost.toFixed(4)}`, `Save ~${costs.savingsPercent.toFixed(0)}%`] : ["Run cost analysis"] },
    { icon: "🌉", title: "Token Migration",       items: ["9-step NTT bridge plan", "Wormhole SDK snippets", "Sunrise liquidity guide"] },
    { icon: "✅", title: "Migration Checklist",   items: ["16 actionable items", "Priority-sorted", "Progress tracking"] },
    { icon: "📚", title: "Resources & Links",     items: ["Anchor, Wormhole, SPL docs", "Sunrise DeFi links", "Metaplex for NFTs"] },
  ];

  return (
    <div>
      {/* Header */}
      <div className="card" style={{ background: "linear-gradient(135deg, var(--bg2), rgba(25,251,155,0.06))", border: "1px solid rgba(25,251,155,0.2)" }}>
        <div className="card-header">
          <span className="card-icon">📄</span>
          <div>
            <div className="card-title">Migration Report — {contractName}</div>
            <div className="card-subtitle">Comprehensive export: analysis · mappings · anchor skeleton · cost · checklist</div>
          </div>
        </div>

        {/* Export buttons */}
        <div className="grid-2" style={{ gap: 16, marginBottom: 16 }}>
          <button
            className="nav-btn primary"
            style={{ padding: "16px", fontSize: 15, fontWeight: 800, display: "flex", alignItems: "center", justifyContent: "center", gap: 10 }}
            onClick={downloadMD}
            disabled={!!exporting}
          >
            {exporting === "md" ? "⟳ Generating…" : "⬇ Download Markdown (.md)"}
          </button>
          <button
            className="nav-btn"
            style={{ padding: "16px", fontSize: 15, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", gap: 10, border: "1px solid rgba(25,251,155,0.4)", color: "var(--accent3)" }}
            onClick={downloadPDF}
            disabled={!!exporting}
          >
            {exporting === "pdf" ? "⟳ Building PDF…" : "⬇ Download PDF"}
          </button>
        </div>
        <p style={{ fontSize: 12, color: "var(--text3)", fontFamily: "var(--mono)", textAlign: "center", margin: 0 }}>
          Markdown opens in any editor · PDF requires jsPDF (loaded on demand)
        </p>
      </div>

      {/* Report contents overview */}
      <div className="card">
        <div className="card-header">
          <span className="card-icon">📋</span>
          <div className="card-title">Report Contents</div>
          <button
            onClick={() => setShowPreview(!showPreview)}
            style={{ marginLeft: "auto", background: "none", border: "1px solid var(--border2)", color: "var(--text2)", fontSize: 12, padding: "6px 14px", borderRadius: "var(--radius)", cursor: "pointer" }}
          >
            {showPreview ? "Hide Preview" : "Preview Markdown"}
          </button>
        </div>

        <div className="grid-2">
          {sections.map((s) => (
            <div key={s.title} style={{ display: "flex", gap: 12, padding: "12px 0", borderBottom: "1px solid var(--border)" }}>
              <span style={{ fontSize: 20, flexShrink: 0 }}>{s.icon}</span>
              <div>
                <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 6 }}>{s.title}</div>
                {s.items.map((item) => (
                  <div key={item} style={{ fontSize: 12, color: "var(--text2)", display: "flex", gap: 6, alignItems: "center", marginBottom: 3 }}>
                    <span style={{ color: "var(--accent3)", fontSize: 10 }}>✓</span> {item}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {showPreview && (
          <div style={{ marginTop: 20, background: "var(--bg)", borderRadius: "var(--radius)", padding: 20, fontFamily: "var(--mono)", fontSize: 11, color: "var(--text2)", maxHeight: 500, overflowY: "auto", lineHeight: 1.8, whiteSpace: "pre-wrap" }}>
            {markdown}
          </div>
        )}
      </div>

      {/* Sunrise emphasis */}
      <div className="card" style={{ border: "1px solid rgba(247,147,26,0.3)", background: "linear-gradient(135deg,rgba(247,147,26,0.05),rgba(153,69,255,0.04))" }}>
        <div className="card-header">
          <span style={{ fontSize: 24 }}>☀</span>
          <div><div className="card-title" style={{ color: "var(--accent)" }}>Included: Sunrise Integration Guide</div><div className="card-subtitle">Full liquidity bootstrapping steps included in report</div></div>
        </div>
        <p style={{ fontSize: 13, color: "var(--text2)", lineHeight: 1.8, marginBottom: 16 }}>
          The exported report includes a dedicated section on <strong>Sunrise DeFi integration</strong> — covering how to register your migrated token, set up day-one AMM liquidity pools, and leverage Sunrise's canonical routing for new Solana assets.
        </p>
        <div style={{ display: "flex", gap: 12 }}>
          <a href="https://www.sunrisedefi.com/" target="_blank" rel="noopener noreferrer" style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: "var(--accent)", color: "#000", fontWeight: 800, fontSize: 14, padding: "12px", borderRadius: "var(--radius)", textDecoration: "none" }}>
            ☀ Apply to Sunrise
          </a>
          <a href="https://wormhole.com/docs/tools/typescript-sdk/get-started/" target="_blank" rel="noopener noreferrer" style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: "var(--bg3)", border: "1px solid var(--border2)", color: "var(--text)", fontWeight: 600, fontSize: 14, padding: "12px", borderRadius: "var(--radius)", textDecoration: "none" }}>
            Wormhole SDK Docs ↗
          </a>
        </div>
      </div>
    </div>
  );
}